using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class RankingPage : MonoBehaviour
{
    List<Tuple<string, int>> RankingData;
    public GameObject RankingContent; //РЮНКЦхХЭ ЧвДч
    public static int rankingCnt = 10; //КИПЉСй ЛѓРЇ ЗЉФПРЧ Мі
    public GameObject RankingContentPrefab;
    List<GameObject> RankingContentChild;
    public ScrollRect scrollRect; //НКХЉЗбКф РЇФЁ АэСЄ
    private float[] pagePositions;

    public PlayFabManager playFabManager; //РЮНКЦхХЭ ЧвДч

    private void Awake()
    {
        RankingData = new List<Tuple<string, int>>();
        if (RankingContent == null || RankingContentPrefab == null)
        {
            Debug.LogError("RankingContentИІ ЧвДчЧЯММПф");
        }
        RankingContentChild = new List<GameObject>();
    }
    //ШАМКШ­ НУПЁ НЧЧр
    private void OnEnable()
    {
        playFabManager.GetLeaderboard(MyLeaderboardCallback);
    }

    public void ShowWorldRanking()
    {
        //ЧСИЎЦеРИЗЮ РкНФ ФмХйУїИІ ЧЅНУЧЯБт + Л§МК
        if (RankingContentChild.Count == 0)
        {
            for (int i = 0; i < rankingCnt; i++)
            {
                GameObject newContent = Instantiate(RankingContentPrefab, RankingContent.transform);
                Text playerName = newContent.GetComponentsInChildren<Text>()[0];
                Text playerScore = newContent.GetComponentsInChildren<Text>()[1];
                Text count = newContent.GetComponentsInChildren<Text>()[2];
                try
                {
                    playerName.text = RankingData[i].Item1;
                    playerScore.text = RankingData[i].Item2.ToString();
                }
                catch
                {
                    Debug.Log("RankingDataПЁ ЕЅРЬХЭАЁ ОјРН");
                }
                count.text = string.Format("{0:00}", i + 1);
                RankingContentChild.Add(newContent);
            }
        }
        else
        {
            for (int i = 0; i < rankingCnt; i++)
            {
                GameObject curContent = RankingContentChild[i];
                Text playerName = curContent.GetComponentsInChildren<Text>()[0];
                Text playerScore = curContent.GetComponentsInChildren<Text>()[1];
                Text count = curContent.GetComponentsInChildren<Text>()[2];

                try
                {
                    playerName.text = RankingData[i].Item1;
                    playerScore.text = RankingData[i].Item2.ToString();                
                }
                catch
                {
                    Debug.Log("RankingDataПЁ ЕЅРЬХЭАЁ ОјРН");
                }
                count.text = string.Format("{0:00}", i + 1);
            }
        }
    }

    public void SetRankingData(List<Tuple<string, int>> data)
    {
        RankingData = data;
    }

    private void Update()
    {      
        if (Input.GetMouseButtonDown(0))
        {
            Vector2 mousePosition = Input.mousePosition/*Camera.main.ScreenToWorldPoint(Input.mousePosition)*/;

            // CanvasАЁ ШАМКШ­ЕЧОю РжАэ ХЌИЏЕШ РЇФЁАЁ Canvas ГЛКЮАЁ ОЦДб АцПь CanvasИІ КёШАМКШ­
            if (this.gameObject.activeSelf
                && !RectTransformUtility.RectangleContainsScreenPoint(this.gameObject.GetComponent<RectTransform>(), mousePosition))
            {
                //ОжДЯИоРЬМЧ РчЛ§
                gameObject.GetComponent<Animation>().Play("RankingPageCloseAnim");
            }
            
        }
    }

    // ОжДЯИоРЬМЧ РЬКЅЦЎПЁМ­ ШЃУтЕЩ ЧдМі
    public void OnAnimationEnd()
    {
        // ОжДЯИоРЬМЧРЬ ГЁГЊИщ CanvasИІ КёШАМКШ­ЧеДЯДй.
        gameObject.SetActive(false);
    }

    //ИЎДѕКИЕхПЁМ­ АЊРЛ АЛНХЧЯИщ Ш­ИщПЁ ЧЅНУ (ФнЙщ)
    public void MyLeaderboardCallback(PlayFab.ClientModels.GetLeaderboardResult result)
    {
        Debug.Log("Leaderboard received successfully!");
        ShowWorldRanking();
    }

}
